### ISSUE TITLE
Support named fields in enum variants

### ISSUE THREAD

**Issue by qvignaud** [ZettaScaleLabs/stabby#23]
Hi all,

I'm currently doing some trials on implementing a dylib-based plugin system on [Mélodium project](https://gitlab.com/melodium/melodium). Stabby sounds very promising, however I got a blocker when dealing about enums with named fields.

Currently applying the `#[stabby::stabby]` marco attribute gives `message: stabby does not support named fields in enum variants`.

We have some of these in our common base crate, and while the project is still on early stage development, we would like to know if support to named fields is something that may come, or if we should consider some design changes within our project to comply to this constraint.

Here are few cases:
- https://gitlab.com/melodium/melodium/-/blob/master/melodium-common/src/descriptor/loader.rs
- https://gitlab.com/melodium/melodium/-/blob/master/melodium-common/src/descriptor/status.rs

Enjoy your day !

**Comment by p-avital** [comment]
Hi,

Thanks for checking out stabby.

While supporting named fields (as well as multiple unnamed fields) in variants is technically feasible, it would make the proc-macros much more complex (not that they're simple to begin with). Since stabby's core goal is to provide reliability and stability, I erred on the side of avoiding that (and the risk of mistakes along with it).

While I never fully _excluded_ the idea of supporting them, I don't see that happenning in the short or middle term, as I have other aspects of stabby (mostly, its standard library) that I want to prioritize.

Have a great day too :)

**Comment by qvignaud** [comment]
I understand your point. We're encountering some limitations on other aspects so we're suspending this PoC for the moment.

I let you decide to close or not this issue.

Great job anyway, impatient to use it more deeply :ok_hand:

**Comment by p-avital** [comment]
Thanks,

Another point I failed to consider, but that supports the "not supporting" side is that pattern matching must be replaced by other techniques (since I can't make the compiler understand `repr(stabby)`, it can't pattern match on it), such as closure based matches or accessors, which kinda need a name for each variant's struct.

If there are other aspects of stabby that you'd like to comment on, I'd be glad to get any feedback / answer any question :)

**Comment by p-avital** [comment]
Hi,

Since I don't think I could make codegen that would yield comfortable-to-use code, I'm closing this issue.

If I get ideas in the future, I'll reopen this issue :)

**Comment by GoldsteinE** [comment]
I get why `#[repr(stabby)]` enums with named fields are not supported, but would it be possible to support `#[repr(C)]` enums? They have the same layout as ones without named fields, so it seems like it wouldn’t complicate the macro too much.

**Comment by GoldsteinE** [comment]
I guess codegen for layout grows somewhat more complicated for multiple-field variants: the easiest way to do it is probably to codegen a fake struct to get a compiler to do layout calculations for us, e.g. if we have an enum like
```
#[stabby]
#[repr(C)]
enum Foo {
    Bar { a: u8, b: u8, c: u8 },
}
```
then `Bar` data has layout equivalent to `ManuallyDrop<Foo_Bar>` where `Foo_Bar` is
```
#[repr(C)]
struct Foo_Bar {
    a: u8, b: u8, c: u8,
}
```

**Comment by p-avital** [comment]
That actually makes a lot of sense @GoldsteinE, I'll check a few things before going through with that, but I'll reopen the issue in the meantime :)

If I don't return to this issue by next week, I likely have forgotten and you may ping me to remind me of it if that feature's important to you :)

**Comment by GoldsteinE** [comment]
Thanks! I’ll try to hack on this locally meanwhile.

**Comment by GoldsteinE** [comment]
> One thing that springs to mind is that repr(C) enum discriminant size are wonky, so I'll do more research, but I might straight up remove support for it if so...

It’s controlled by the `c-enum-min-bits` target option. I’m not sure if there’s a better way to extract this information than 

```rust
#[repr(C)] enum Empty {
    Variant,
}

size_of::<Empty>()
```

Requiring to manually specify discriminant size via e.g. `#[repr(i32)]` may be reasonable.

**Comment by p-avital** [comment]
Thanks for the hint. I think it's doable. I'll try and do that this weekend, and also stabilize multi-field variants in all non-`repr(stabby)` enums :)

**Comment by p-avital** [comment]
Alright! Support for this is now merged into `main`, although I still want to get a few things done for the next release :)

**Comment by GoldsteinE** [comment]
Thank you!
