### ISSUE TITLE
`rustc` stuck during macro expansion

### ISSUE THREAD

**Issue by gschulze** [ZettaScaleLabs/stabby#28]
`rustc` is stuck at 100% CPU compiling the following code snippet:

```rust
use stabby::dynptr;

#[stabby::stabby]
trait Config {
    fn eq(&self, other: DynConfig) -> bool {
        todo!()
    }
}

type DynConfig = dynptr!(&dyn Config);
```

Moreover, when setting `DynConfig` to point to a different trait, e.g. `Config2`, the following error is reported:

```
error[E0605]: non-primitive cast: `for<'a> fn(&'a StabbyArbitraryType, stabby::DynRef<'static, <(dyn Config2 + 'static) as stabby::stabby_abi::vtable::CompoundVt>::Vt<stabby::stabby_abi::vtable::VtDrop>>) -> bool {<StabbyArbitraryType as Config>::eq}` as `for<'a> extern "C" fn(&'a StabbyArbitraryType, stabby::DynRef<'static, stabby::stabby_abi::vtable::VTable<StabbyVtableConfig2>>) -> bool`
```

Is what I am trying to achieve currently supported by the library? Nevertheless, great work!

**Comment by p-avital** [comment]
Oooh, that's a fun one.

The first one is probably because of using a "dyn ThisTrait", which I might have forgotten to check. I'll have to check it out, thanks for letting me know.

The second is definitely because of the default implementation. I think it's supportable, but for now, consider it unsupported.

**Comment by gschulze** [comment]
Cool, looking forward to the next release! Regarding the second issue, I didn't mean to put a default implementation here, so if the basic case works that's fine. Let me know if I can help!

**Comment by p-avital** [comment]
Hiya @gschulze, just letting you know I haven't forgotten you, I just don't have much time on hand at the moment to investigate the issue. I'll probably be able to check it out next week or the following :)

**Comment by p-avital** [comment]
Hi @gschulze,

Just started investigating, here are my current findings:
- The conversion error wasn't actually because of the default implementation, but because I had recently made the macro allow you to write `fn eq` without specifying an ABI. I'm going to revert that change, and might reintroduce it by annotating everything by `extern "C"` if you don't specify else wise.
- I've been able to reproduce the rustc hanging, but that seems to come from the compiler and not the proc macro: I've checked by expanding the macro, and it does hang too... I'll try to minimize the example and check with Rust team if that's fixable :)

**Comment by p-avital** [comment]
Good news @gschulze, I've just made a new release of stabby that addresses both issues, thanks for pointing them out \o/

**Comment by gschulze** [comment]
Hey @p-avital, thanks a lot for the quick fix, will try it out as soon as possible!

**Comment by p-avital** [comment]
As an aside, I'm now in the process of implementing `stabby::IStable` for the types in `abi_stable`. If there are any of these types that you need to use, let me know and I'll make sure they make it into the next PR, which will also add more checks to ensure stabby doesn't mis-evaluate some type and UB all the `repr(stabby)` enums.
